In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\ADMIN\Downloads\Copper_Set.xlsx - Result 1.csv")
df.head()

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8928\1782451106.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\ADMIN\Downloads\Copper_Set.xlsx - Result 1.csv")

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00

In [3]:
df.shape

(181673, 14)

In [4]:

# from dataprep.eda import create_report
# # create_report(df)

In [5]:
# !pip install dataprep

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181673 entries, 0 to 181672
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             181671 non-null  object
 1   item_date      181672 non-null  float64
 2   quantity tons  181673 non-null  object
 3   customer       181672 non-null  float64
 4   country        181645 non-null  float64
 5   status         181671 non-null  object
 6   item type      181673 non-null  object
 7   application    181649 non-null  float64
 8   thickness      181672 non-null  float64
 9   width          181673 non-null  float64
 10  material_ref   103754 non-null  object
 11  product_ref    181673 non-null  int64
 12  delivery date  181672 non-null  float64
 13  selling_price  181672 non-null  float64
dtypes: float64(8), int64(1), object(5)
memory usage: 19.4+ MB

In [7]:
df.isna().sum()

id                   2
item_date            1
quantity tons        0
customer             1
country             28
status               2
item type            0
application         24
thickness            1
width                0
material_ref     77919
product_ref          0
delivery date        1
selling_price        1
dtype: int64

In [8]:
d=df[df['id'].isna()]

In [9]:
df.drop(d.index,inplace=True)

In [10]:
df['id'].isnull().sum()

0

In [11]:
df.set_index("id",inplace=True)

In [12]:
df.head()

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,104991,1668701718,20210401.0,1047.00
E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00

In [13]:
data=df[df['item_date'].isna()]
data

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
1BA92915-36FC-437A-811C-9DC7BF958EA6,NaN,51.785585,30230331.0,80.0,Lost,S,10.0,0.9,1435.0,NaN,628377,20210101.0,654.0

In [14]:
newdata=df[(df['delivery date']==20210101.0 )& (df['country']==80.0)&(df['status']=="Lost") & (df['item type']=="S") & (df['application']==10.0)]
newdata

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
E233484C-1B2A-433E-AC5A-021C1D67B33E,20201119.0,358.021777,30230164.0,80.0,Lost,S,10.0,3.0,2000.0,NaN,640665,20210101.0,606.0
9E3BA6CC-1E2D-4475-80CF-9AC6FE493852,20201112.0,59.150007,30230331.0,80.0,Lost,S,10.0,0.7,1425.0,NaN,628377,20210101.0,656.0
E5DB525E-7C9D-4547-ADF6-394B16A8784F,20201112.0,58.611558,30230331.0,80.0,Lost,S,10.0,0.7,1450.0,NaN,628377,20210101.0,660.0
157A60A2-16AE-45EE-94D5-93B7A19D5638,20201112.0,55.563126,30230331.0,80.0,Lost,S,10.0,0.7,1304.0,NaN,628377,20210101.0,661.0
D6B0EF82-098D-43AC-9E92-D7074A700485,20201112.0,52.988369,30230331.0,80.0,Lost,S,10.0,0.8,1250.0,NaN,628377,20210101.0,651.0
4524FC41-1793-4944-BE92-A8816CFE203D,20201112.0,55.32128,30230331.0,80.0,Lost,S,10.0,0.8,1373.0,NaN,628377,20210101.0,656.0
B93AD8F5-7105-44CF-8557-6660622540B9,20201112.0,54.3167,30230331.0,80.0,Lost,S,10.0,0.8,1450.0,NaN,628377,20210101.0,648.0
1BA92915-36FC-437A-811C-9DC7BF958EA6,NaN,51.785585,30230331.0,80.0,Lost,S,10.0,0.9,1435.0,NaN,628377,20210101.0,654.0
F51323C6-D171-433C-BF5B-4A12874D55D4,20201112.0,57.628043,30230331.0,80.0,Lost,S,10.0,0.6,1280.0,NaN,628377,20210101.0,667.0
C4BAA2D0-B425-43B6-B0CD-40B98531E018,20201112.0,51.497893,30230331.0,80.0,Lost,S,10.0,1.2,1385.0,NaN,628377,20210101.0,650.0
90D90452-1773-4CC6-9577-E24B62246C71,20201112.0,56.954641,30230331.0,80.0,Lost,S,10.0,1.2,1236.0,NaN,628377,20210101.0,648.0
6C1CDDF4-F748-41F2-879F-9D0E58DD6C8D,20201103.0,127.444385,30291680.0,80.0,Lost,S,10.0,8.0,1500.0,NaN,640665,20210101.0,564.0
7E74ABB5-DCE6-4DE3-AE1F-3496A60BDF4C,20201103.0,63.177616,30291680.0,80.0,Lost,S,10.0,4.9,1500.0,NaN,640665,20210101.0,565.0
54488094-8A6A-4454-B7FA-ED806E5D770E,20201103.0,151.357789,30291680.0,80.0,Lost,S,10.0,10.0,1500.0,NaN,640665,20210101.0,568.0
E055350A-FCA8-4BE3-8ECC-2E763F8D605D,20201103.0,128.520316,30291680.0,80.0,Lost,S,10.0,7.9,1500.0,NaN,640665,20210101.0,567.0
0AE01885-1C02-4F64-85A5-A35EB0FF6873,20201103.0,68.3386,30291680.0,80.0,Lost,S,10.0,5.9,1500.0,NaN,640665,20210101.0,559.0
C30A4C9B-9D60-4E69-AF27-BF0462964824,20201103.0,159.240318,30291680.0,80.0,Lost,S,10.0,9.9,1500.0,NaN,640665,20210101.0,572.0

In [15]:
k=df[df['item_date'].isnull()]
k

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
1BA92915-36FC-437A-811C-9DC7BF958EA6,NaN,51.785585,30230331.0,80.0,Lost,S,10.0,0.9,1435.0,NaN,628377,20210101.0,654.0

In [16]:
new_date=newdata['item_date'].value_counts().index[0]
new_date

20201112.0

In [17]:
df['item_date'].unique()

array([20210401., 19950000., 20210331., 20210330., 20210329., 20210328.,
       20210327., 20210326., 20210325., 20210324., 20210323., 20210322.,
       20210319., 20210318., 20210317., 20210316., 20210315., 20210314.,
       20210313., 20210312., 20210311., 20210310., 20210309., 20210308.,
       20210307., 20210306., 20210305., 20210304., 20210303., 20210302.,
       20210301., 20210228., 20210227., 20210226., 20210225., 20210224.,
       20210223., 20210222., 20210221., 20210220., 20210219., 20210218.,
       20210217., 20210216., 20210215., 20210214., 20210213., 20210212.,
       20210211., 20210210., 20210209., 20210208., 20210207., 20210205.,
       20210204., 20210203., 20210202., 20210201., 20210131., 20210130.,
       20210129., 20210128., 20210127., 20210126., 20210125., 20210124.,
       20210122., 20210121., 20210120., 20210119., 20210118., 20210117.,
       20210116., 20210115., 20210114., 20210113., 20210112., 20210111.,
       20210110., 20210109., 20210108., 20210107., 20210106., 20210105.,
       20210104., 20210103., 20201231., 20201230., 20201229., 20201228.,
       20201227., 20201226., 20201224., 20201223., 20201222., 20201221.,
       20201219., 20201218., 20201217., 20201216., 20201215., 20201214.,
       20201213., 20201212., 20201211., 20201210., 20201209., 20201208.,
       20201207., 20201206., 20201205., 20201204., 20201203., 20201202.,
       20201201., 20201130., 20201129., 20201128., 20201127., 20201126.,
       20201125., 20201124., 20201123., 20201122., 20201120., 20201119.,
       20201118., 20201117., 20201116., 20201115., 20201114., 20201113.,
       20201112.,       nan, 20201111., 20191919., 20201110., 20201109.,
       20201106., 20201105., 20201104., 20201103., 20201102., 20201101.,
       20201030., 20201029., 20201028., 20201027., 20201026., 20201025.,
       20201024., 20201023., 20201022., 20201021., 20201020., 20201019.,
       20201018., 20201016., 20201015., 20201014., 20201013., 20201012.,
       20201011., 20201009., 20201008., 20201007., 20201006., 20201005.,
       20201004., 20201002., 20201001., 20200930., 20200929., 20200928.,
       20200925., 20200924., 20200923., 20200922., 20200921., 20200920.,
       20200919., 20200918., 20200917., 20200916., 20200915., 20200914.,
       20200913., 20200911., 20200910., 20200909., 20200908., 20200907.,
       20200906., 20200905., 20200904., 20200903., 20200902., 20200901.,
       20200831., 20200829., 20200828., 20200827., 20200826., 20200825.,
       20200824., 20200822., 20200821., 20200820., 20200819., 20200818.,
       20200817., 20200815., 20200814., 20200813., 20200812., 20200811.,
       20200810., 20200809., 20200807., 20200806., 20200805., 20200804.,
       20200803., 20200802., 20200801., 20200731., 20200730., 20200729.,
       20200728., 20200727., 20200726., 20200724., 20200723., 20200722.,
       20200721., 20200720., 20200719., 20200718., 20200717., 20200716.,
       20200715., 20200714., 20200713., 20200712., 20200710., 20200709.,
       20200708., 20200707., 20200706., 20200705., 20200704., 20200703.,
       20200702.])

In [18]:
df.loc[df['item_date'].isnull()==True, 'item_date']

id
1BA92915-36FC-437A-811C-9DC7BF958EA6   NaN
Name: item_date, dtype: float64

In [19]:
df.loc[df['item_date'].isnull()==True, 'item_date']=new_date

In [20]:
df['item_date'].isnull().sum()

0

In [21]:
quantity=df[df['quantity tons']=='e']

In [22]:
df.drop(quantity.index,inplace=True)

In [23]:
df['item_date'].isnull().sum()

0

In [24]:
df[df['quantity tons']=='e']

Empty DataFrame
Columns: [item_date, quantity tons, customer, country, status, item type, application, thickness, width, material_ref, product_ref, delivery date, selling_price]
Index: []

In [25]:
df['quantity tons']=df['quantity tons'].astype('float')

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181670 entries, EC06F063-9DF0-440C-8764-0B0C05A4F6AE to AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item_date      181670 non-null  float64
 1   quantity tons  181670 non-null  float64
 2   customer       181669 non-null  float64
 3   country        181642 non-null  float64
 4   status         181668 non-null  object
 5   item type      181670 non-null  object
 6   application    181646 non-null  float64
 7   thickness      181669 non-null  float64
 8   width          181670 non-null  float64
 9   material_ref   103753 non-null  object
 10  product_ref    181670 non-null  int64
 11  delivery date  181669 non-null  float64
 12  selling_price  181669 non-null  float64
dtypes: float64(9), int64(1), object(3)
memory usage: 19.4+ MB

In [27]:
customer=df[df['customer'].isnull()]

In [28]:
df.drop(customer.index,inplace=True)

In [29]:
df['customer'].isnull().sum()

0

In [30]:
df[df['status'].isnull()]

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
A5FBB960-C2BF-4956-8B4A-CD60495541D3,20201111.0,101.342459,30287258.0,27.0,NaN,S,10.0,0.68,940.0,750928009B2F60HEA,611993,20210101.0,862.0
F6E1BBAE-B27F-42B5-87C8-EE36415C18A6,20201111.0,50.532524,30287258.0,27.0,NaN,S,10.0,0.58,908.0,405029489B2F60HEA,611993,20210101.0,899.0

In [31]:
df['status'].unique()

array(['Won', 'Draft', 'To be approved', 'Lost', 'Not lost for AM',
       'Wonderful', 'Revised', 'Offered', 'Offerable', nan], dtype=object)

In [32]:
# status=df[(df['item_date']==20201111.0) & (df['customer']==30287258.0)&(df['country']==27.0) &(df['item type']=="S")&(df['application']==10.0)&(df['product_ref']==611993)&(df['delivery date']==20210101.0)]
# status
# new_status=status['status'].value_counts().index[0]
# new_status

In [33]:
# df['status']=df.loc[df['status'].isnull()==True,'status']=new_status

In [34]:
df['customer'].isnull().sum()

0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181669 entries, EC06F063-9DF0-440C-8764-0B0C05A4F6AE to AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item_date      181669 non-null  float64
 1   quantity tons  181669 non-null  float64
 2   customer       181669 non-null  float64
 3   country        181641 non-null  float64
 4   status         181667 non-null  object
 5   item type      181669 non-null  object
 6   application    181645 non-null  float64
 7   thickness      181668 non-null  float64
 8   width          181669 non-null  float64
 9   material_ref   103753 non-null  object
 10  product_ref    181669 non-null  int64
 11  delivery date  181668 non-null  float64
 12  selling_price  181668 non-null  float64
dtypes: float64(9), int64(1), object(3)
memory usage: 19.4+ MB

In [36]:
df['application'].value_counts()

10.0    77542
41.0    46260
15.0    20772
59.0     8926
42.0     5858
56.0     4846
29.0     1937
27.0     1784
26.0     1650
28.0     1591
40.0     1576
25.0     1498
79.0     1422
22.0     1023
20.0      768
66.0      718
3.0       657
38.0      511
58.0      447
4.0       286
39.0      267
65.0      247
67.0      221
68.0      181
99.0      146
19.0      143
69.0      122
5.0       110
70.0      102
2.0        34
Name: application, dtype: int64

In [37]:
df[df['customer'].isnull()]

Empty DataFrame
Columns: [item_date, quantity tons, customer, country, status, item type, application, thickness, width, material_ref, product_ref, delivery date, selling_price]
Index: []

In [38]:
df[df['application'].isnull()]['customer'].max()

2147483647.0

In [39]:
customer=df[(df['item_date']==20201112.0) & (df['customer']==2147483647.0)& (df['status']=='Not lost for AM') & (df['width']==1500)&(df['product_ref']==640405) & (df['delivery date']==20210101.0) ]
customer
# customer['country']=customer['country'].fillna(0)
# customer['application']=customer['application'].fillna(0)


# customer[['country','application']]=customer.loc[customer[['country','application']]==0][['country','application']]

Empty DataFrame
Columns: [item_date, quantity tons, customer, country, status, item type, application, thickness, width, material_ref, product_ref, delivery date, selling_price]
Index: []

In [40]:
# df['country']=customer['country'].fillna(0)
df['application']=df['application'].fillna(0)
# df.head()

In [41]:
df['application'].isnull().sum()

0

In [42]:
df.head()

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,104991,1668701718,20210401.0,1047.00
E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00

In [43]:
customer=df[ (df['customer']==30291680.0)]

In [44]:
# df['customer']=df.loc[df['customer'].is]

In [45]:
df.isnull().sum()

item_date            0
quantity tons        0
customer             0
country             28
status               2
item type            0
application          0
thickness            1
width                0
material_ref     77916
product_ref          0
delivery date        1
selling_price        1
dtype: int64

In [46]:
df[df['country'].isnull()]

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
DA084B55-6789-4CC4-9F4F-361EE7C2614C,20201112.0,127.243871,3.019689e+07,NaN,Not lost for AM,S,10.0,3.50,1220.0,NaN,1668701718,20210201.0,810.0
EA5FCEBF-D8D8-43D3-9CFB-9134634764CE,20201112.0,108.751059,3.019927e+07,NaN,Lost,S,10.0,3.50,1220.0,NaN,164141591,20210401.0,847.0
4433B483-7929-4DE7-B467-6263B3C02DDF,20201112.0,30.156899,3.034185e+07,NaN,Not lost for AM,S,41.0,0.60,1250.0,NaN,611993,20210201.0,1099.0
B689A281-5701-4D9A-B6C3-25BEA51B1656,20201112.0,52.086808,3.019859e+07,NaN,Not lost for AM,S,59.0,3.65,1409.0,MP0365PRSCJR1409,640665,20210101.0,575.0
AE2513DD-4289-4B80-9F5A-C05F5FE14FA0,20201105.0,34.200136,2.147484e+09,NaN,To be approved,S,0.0,5.00,1500.0,NaN,640405,20210101.0,630.0
A42A4216-082E-447E-9DA8-8FA43AAFDBE2,20201105.0,33.491866,2.147484e+09,NaN,Draft,S,0.0,6.00,1500.0,NaN,640405,20210101.0,19.0
6CC87C58-D6BB-45F1-A2C2-637DA1E0E4A5,20201105.0,29.133722,2.147484e+09,NaN,Draft,S,0.0,8.00,1500.0,NaN,640405,20210101.0,12.0
12EDD093-C1E3-4224-A367-AF9BC982519B,20201105.0,33.533078,2.147484e+09,NaN,Draft,S,0.0,9.99,1500.0,NaN,640405,20210101.0,21.0
48CC05C8-17E7-49E1-ADD9-5B88CF8E6E5F,20201105.0,25.518348,2.147484e+09,NaN,Draft,S,0.0,11.99,1500.0,NaN,640405,20210101.0,21.0
1D41F861-31AC-4177-97A3-F1AE6641A0F7,20201105.0,27.274928,2.147484e+09,NaN,Draft,S,0.0,14.99,1500.0,NaN,640405,20210101.0,20.0
6BFB864D-7287-4E9B-BC5E-7DEB16ACF0D5,20201105.0,33.130689,2.147484e+09,NaN,Draft,S,0.0,5.00,1500.0,NaN,640405,20210101.0,12.0
3BF4C439-BFD5-47C5-9A61-03F2E88E0803,20201105.0,25.582634,2.147484e+09,NaN,Draft,S,0.0,6.00,1500.0,NaN,640405,20210101.0,22.0
69CB191E-CF03-4136-BA99-E1C2C3328A9B,20201105.0,26.776187,2.147484e+09,NaN,Draft,S,0.0,8.00,1500.0,NaN,640405,20210101.0,11.0
FDE1A57E-799F-4BC3-966C-8F50A99438DC,20201105.0,25.246040,2.147484e+09,NaN,Draft,S,0.0,9.99,1500.0,NaN,640405,20210101.0,21.0
6070CFAF-51CE-4860-A469-7B0D745AAD58,20201105.0,27.954986,2.147484e+09,NaN,Draft,S,0.0,11.99,1500.0,NaN,640405,20210101.0,14.0
2BF4E093-BEF6-4D2A-B6BC-4098F17064F6,20201105.0,33.011682,2.147484e+09,NaN,Draft,S,0.0,14.99,1500.0,NaN,640405,20210101.0,13.0
164992DB-9711-43A7-99C8-2A3F5A70E322,20201105.0,30.427124,2.147484e+09,NaN,Draft,S,0.0,4.00,1500.0,NaN,640405,20210101.0,17.0
878A4018-B936-404A-B7C2-B1FF4F5E3B3E,20201105.0,28.125144,2.147484e+09,NaN,Draft,S,0.0,5.00,1500.0,NaN,640405,20210101.0,11.0
72A7A1A0-1178-4358-BAB9-298CD13C4C26,20201105.0,31.787567,2.147484e+09,NaN,Draft,S,0.0,6.00,1500.0,NaN,640405,20210101.0,14.0
0B789376-610A-4357-8577-BF9008D0435A,20201105.0,31.994011,2.147484e+09,NaN,Draft,S,0.0,8.00,1500.0,NaN,640405,20210101.0,22.0
A2EC4607-A229-403C-8B84-EB3D7D9BADFC,20201105.0,27.292523,2.147484e+09,NaN,Draft,S,0.0,4.00,1500.0,NaN,640405,20210101.0,18.0
C34899F6-7879-4275-ACBF-35640D04FB39,20201105.0,28.858731,2.147484e+09,NaN,Draft,S,0.0,5.00,1500.0,NaN,640405,20210101.0,21.0
E373145A-38FE-4B23-8A31-804DB3C582C2,20201105.0,31.388466,2.147484e+09,NaN,Draft,S,0.0,6.00,1500.0,NaN,640405,20210101.0,21.0
B5851D97-D994-4EA6-9016-7F77C853A051,20201105.0,34.821347,2.147484e+09,NaN,Draft,S,0.0,8.00,1500.0,NaN,640405,20210101.0,18.0
DD68F1B7-7F12-43F4-ADB0-8CECAD6D130D,20201022.0,1509.182917,2.147484e+09,NaN,Lost,S,0.0,12.00,1500.0,NaN,640665,20210101.0,707.0
AB4948AD-5BE4-4260-BB8A-A841C6F791A7,20201022.0,501.422024,2.147484e+09,NaN,Not lost for AM,S,0.0,12.00,1500.0,NaN,640405,20210101.0,750.0
C39AA030-A021-471E-B403-1F7B734F3304,20201002.0,31.301207,2.147484e+09,NaN,Lost,W,0.0,4.00,1500.0,NaN,640405,20201201.0,811.0
1BB34C35-BBA9-4B51-8F20-3C0576654DDB,20201002.0,30.154695,2.147484e+09,NaN,Lost,W,0.0,5.00,1500.0,NaN,640405,20201201.0,781.0

In [47]:
# df['country']=df[df['application']==0.0]= 0

In [48]:
# df[df['country'].isnull()]

In [49]:
df.loc[(df['customer']==2147483647.0)&(df['country'].isnull()==True),'country']=0
# df['country']

In [50]:
df['country'].isnull().sum()

4

In [51]:
df[df['country'].isnull()]

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
DA084B55-6789-4CC4-9F4F-361EE7C2614C,20201112.0,127.243871,30196886.0,NaN,Not lost for AM,S,10.0,3.50,1220.0,NaN,1668701718,20210201.0,810.0
EA5FCEBF-D8D8-43D3-9CFB-9134634764CE,20201112.0,108.751059,30199273.0,NaN,Lost,S,10.0,3.50,1220.0,NaN,164141591,20210401.0,847.0
4433B483-7929-4DE7-B467-6263B3C02DDF,20201112.0,30.156899,30341846.0,NaN,Not lost for AM,S,41.0,0.60,1250.0,NaN,611993,20210201.0,1099.0
B689A281-5701-4D9A-B6C3-25BEA51B1656,20201112.0,52.086808,30198586.0,NaN,Not lost for AM,S,59.0,3.65,1409.0,MP0365PRSCJR1409,640665,20210101.0,575.0

In [52]:
df[df['customer']==30198586.0]

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
6A8BB534-EC96-450D-A706-DF6EE1A0FB52,20210401.0,31.760121,30198586.0,27.0,Won,S,59.0,0.6,1000.0,MP0060PODEFS1000,628377,20210801.0,989.0
B86DF445-11EC-4165-8F98-3B82E8820E70,20210401.0,27.280709,30198586.0,27.0,Won,S,59.0,0.6,1250.0,MP0060PODEFS1250,628377,20210801.0,974.0
C05F5D7D-EADA-4310-8135-EA38B439F4D0,20210401.0,20.152395,30198586.0,27.0,Won,S,59.0,0.6,1500.0,MP0060PODEFS1500,628377,20210801.0,968.0
67A3CE5E-870D-4F37-8AEC-18AAD097ED3C,20210331.0,103.105797,30198586.0,27.0,Won,S,59.0,0.7,1000.0,MP0070PODEFS1000,628377,20210801.0,980.0
50AC9022-3385-4CC9-B67F-A98FB5560C29,20210331.0,98.083263,30198586.0,27.0,Won,S,59.0,0.7,1250.0,MP0070PODEFS1250,628377,20210801.0,973.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
843544AA-E36B-411E-808E-1849AC265BC0,20200706.0,31.085434,30198586.0,27.0,Won,S,59.0,9.5,1005.0,NaN,640665,20200701.0,461.0
40FD447C-33C6-4875-B48D-BD86E352FDEC,20200706.0,32.944049,30198586.0,27.0,Won,S,59.0,12.0,1474.0,NaN,640665,20200701.0,465.0
C81B442A-8C62-442C-AB16-8DD8FD779999,20200706.0,32.515822,30198586.0,27.0,Won,S,59.0,3.3,1786.0,NaN,640665,20200701.0,459.0
6D4A267B-6E75-46BE-A420-97110AC18C20,20200706.0,33.394607,30198586.0,27.0,Won,S,59.0,12.0,1674.0,NaN,640665,20200701.0,456.0
D1A4E696-1373-45B5-8376-54745438670A,20200706.0,29.232196,30198586.0,27.0,Won,S,59.0,9.5,1650.0,NaN,640665,20200701.0,456.0

In [53]:
df[df['customer']==30196886.0]

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
28FFE9BA-B9C0-4FBD-8AD2-14C24DA37B73,20210330.0,501.608513,30196886.0,84.0,Not lost for AM,S,10.0,2.0,1050.0,NaN,1668701718,20210701.0,1243.0
CC1F8955-F1AC-4571-AF67-92529B032E34,20210330.0,1002.058832,30196886.0,84.0,Not lost for AM,S,10.0,2.5,1050.0,NaN,1668701718,20210701.0,1245.0
94C21F40-F46E-418E-80AA-C85818D6C0CB,20210329.0,1080.035109,30196886.0,84.0,Lost,W,10.0,16.0,1255.0,NaN,640665,20220101.0,1003.0
70F33FE7-63F6-4177-BC01-48E7EE154AEB,20210329.0,1075.110061,30196886.0,84.0,Lost,W,10.0,12.0,1710.0,NaN,640665,20220101.0,1002.0
230684A7-6716-4B08-9AD7-1DD13D0066A5,20210329.0,1079.945988,30196886.0,84.0,Lost,W,10.0,16.0,975.0,NaN,640665,20220101.0,1015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4AE76F44-F099-4C99-BE40-FD0ABFD4C679,20200703.0,28.513071,30196886.0,84.0,Not lost for AM,S,10.0,1.0,1075.0,310190,611993,20200101.0,919.3
E29C0B41-51B0-4285-910C-FB59FCB35FD5,20200703.0,34.113792,30196886.0,84.0,Not lost for AM,S,10.0,1.0,1075.0,310191,611993,20200101.0,920.3
2B59F79E-A9A4-479E-9494-56358DB5AE35,20200703.0,29.430681,30196886.0,84.0,Not lost for AM,S,10.0,1.0,1075.0,310193,611993,20200101.0,925.3
2AC7851B-C572-40B6-AB23-8E6A9C4267F2,20200703.0,900.055127,30196886.0,84.0,Won,S,10.0,1.5,1282.0,S550GD+ZM,1668701718,20200801.0,736.0
3944610A-0F1D-481A-9DA6-3D302CF16851,20200702.0,4005.462722,30196886.0,84.0,Lost,S,10.0,5.0,1219.0,NaN,640665,20200801.0,532.0

In [54]:
df[df['customer']==30199273.0]

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
F1009988-4671-4D2D-A30C-C5A26DA42FC8,20210329.0,32.428176,30199273.0,27.0,Lost,S,10.0,1.50,1250.0,NaN,1668701718,20210801.0,1169.0
0841A0B7-00D6-4CEB-8194-BD9938D99D7E,20210329.0,76.272479,30199273.0,27.0,Won,S,10.0,5.00,980.0,NaN,1668701718,20210801.0,1084.0
B87F3E4A-D955-47D0-9870-87055BC38A28,20210329.0,106.717301,30199273.0,27.0,Lost,S,10.0,0.38,1200.0,38358,611993,20210801.0,1350.0
029D1BBF-81BA-4E60-8BE2-FE410F0A2830,20210329.0,35.209245,30199273.0,27.0,Lost,S,10.0,0.38,1200.0,105608,611993,20210801.0,1380.0
EC008A52-4F59-4533-ACC5-C4D7EDA83AED,20210329.0,330.004596,30199273.0,27.0,Lost,S,10.0,1.00,1167.0,NaN,1332077137,20210801.0,1109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795E0C68-8F2A-42A1-B920-EDEE12051ECF,20200707.0,24.342987,30199273.0,27.0,Lost,S,10.0,4.00,1500.0,NaN,1668701718,20200901.0,707.0
BEAF6090-0C91-418B-A627-2E12ABB2C3CA,20200707.0,132.546060,30199273.0,27.0,Lost,S,10.0,8.00,1440.0,NaN,640405,20200901.0,630.0
EB1AAB6A-EB17-4012-89F9-75949953AF68,20200707.0,55.441733,30199273.0,27.0,Won,S,10.0,2.00,1500.0,90945,611993,20201001.0,742.0
0E7CD041-D184-404D-A940-9C1FEF48DC94,20200706.0,107.552615,30199273.0,27.0,Won,S,10.0,0.48,1230.0,NaN,611993,20201001.0,790.0
B3408EFE-0C5F-4527-B7D4-8C873308FCEB,20200706.0,103.571528,30199273.0,27.0,Won,S,10.0,0.48,1250.0,NaN,611993,20201001.0,794.0

In [55]:
d=df[df['customer']==30341846.0]
df.drop(d.index,inplace=True)

In [56]:
df[df['country'].isnull()]

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
DA084B55-6789-4CC4-9F4F-361EE7C2614C,20201112.0,127.243871,30196886.0,NaN,Not lost for AM,S,10.0,3.50,1220.0,NaN,1668701718,20210201.0,810.0
EA5FCEBF-D8D8-43D3-9CFB-9134634764CE,20201112.0,108.751059,30199273.0,NaN,Lost,S,10.0,3.50,1220.0,NaN,164141591,20210401.0,847.0
B689A281-5701-4D9A-B6C3-25BEA51B1656,20201112.0,52.086808,30198586.0,NaN,Not lost for AM,S,59.0,3.65,1409.0,MP0365PRSCJR1409,640665,20210101.0,575.0

In [58]:
lis=[]
d=len(df[df['country'].isnull()]['customer'])
for i in range(d):
    customer=df[df['country'].isnull()]['customer'][i]
    aa=df[df['customer']==customer]['country'].max()
    df.loc[(df['customer']==customer)&(df['country'].isnull()==True),'country']=aa
    print(aa)
    print(customer)

27.0
30199273.0

In [59]:
df['country'].isnull().sum()

0

In [60]:
# lis=[]
# d=len(df[df['country'].isnull()]['customer'])
# for i in range(d):
#     customer=df[df['country'].isnull()]['customer'][i]
#     aa=df[df['customer']==customer]['country'].max()
#     df.loc[(df['customer']==customer)&(df['country'].isnull()==True),'country']=aa
#     print(aa)
#     print(customer)

In [61]:
df.isnull().sum()

item_date            0
quantity tons        0
customer             0
country              0
status               2
item type            0
application          0
thickness            1
width                0
material_ref     77915
product_ref          0
delivery date        1
selling_price        1
dtype: int64

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181668 entries, EC06F063-9DF0-440C-8764-0B0C05A4F6AE to AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item_date      181668 non-null  float64
 1   quantity tons  181668 non-null  float64
 2   customer       181668 non-null  float64
 3   country        181668 non-null  float64
 4   status         181666 non-null  object
 5   item type      181668 non-null  object
 6   application    181668 non-null  float64
 7   thickness      181667 non-null  float64
 8   width          181668 non-null  float64
 9   material_ref   103753 non-null  object
 10  product_ref    181668 non-null  int64
 11  delivery date  181667 non-null  float64
 12  selling_price  181667 non-null  float64
dtypes: float64(9), int64(1), object(3)
memory usage: 19.4+ MB

In [63]:
d=df[df['thickness'].isnull()]

In [64]:
df.drop(d.index,inplace=True)

In [65]:
d=df[df['delivery date'].isnull()]
d

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
B9C4BAAE-25C3-468F-B315-63D57FA31C15,20201112.0,100.229137,30349338.0,26.0,Won,S,10.0,1.0,1300.0,NaN,611993,NaN,1005.0

In [66]:
a=df[(df['customer']==30349338.0) &(df['status']=='Not lost for AM')]
k=a['delivery date'].value_counts().index[0]
k

20201001.0

In [67]:
df.loc[df['delivery date'].isnull()==True ,'delivery date']=k

In [68]:
df[df['delivery date'].isnull()]

Empty DataFrame
Columns: [item_date, quantity tons, customer, country, status, item type, application, thickness, width, material_ref, product_ref, delivery date, selling_price]
Index: []

In [69]:
df.isnull().sum()

item_date            0
quantity tons        0
customer             0
country              0
status               2
item type            0
application          0
thickness            0
width                0
material_ref     77914
product_ref          0
delivery date        0
selling_price        1
dtype: int64

In [70]:
d=df[df['selling_price'].isnull()]
d

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
78C43232-2EB9-4AD7-899E-0E0BE14B2AE8,20201112.0,25.814926,30349625.0,80.0,Lost,S,15.0,1.2,1250.0,NaN,628377,20210101.0,NaN

In [71]:
df.drop(d.index,inplace=True)

In [72]:
df.isnull().sum()

item_date            0
quantity tons        0
customer             0
country              0
status               2
item type            0
application          0
thickness            0
width                0
material_ref     77913
product_ref          0
delivery date        0
selling_price        0
dtype: int64

In [73]:
df[df['material_ref'].isnull()]

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
EE7EE006-15B3-47A5-A48D-70D54C6B734C,20210401.0,27.512545,30165529.0,78.0,Won,W,10.0,0.75,1250.0,NaN,164141591,20210701.0,1098.0
99659229-166B-4966-AA1F-9796DA6055DB,20210401.0,10.411350,30271717.0,28.0,To be approved,W,10.0,0.60,1250.0,NaN,611993,20210701.0,1258.0
9CEF626C-6124-4C5C-9D54-0E5B8A8F2782,20210401.0,16.253987,30271717.0,28.0,To be approved,W,10.0,0.80,1250.0,NaN,611993,20210701.0,1193.0
93B04F7B-0A4C-4D45-AB3A-67DB7888869A,20210401.0,14.203574,30271717.0,28.0,To be approved,W,10.0,0.60,1000.0,NaN,611993,20210701.0,1265.0
D8ABD8F4-7A72-446E-8C91-4C9FBF240EF3,20210401.0,9.822404,30271717.0,28.0,To be approved,W,10.0,1.00,1250.0,NaN,611993,20210701.0,1186.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
F5EC467C-300D-4E85-BEF7-51999E0B7CA7,20200702.0,1.672379,30155929.0,25.0,Won,W,41.0,0.58,1220.0,NaN,611993,20200701.0,776.0
497F5391-F450-4B49-870D-9B62A0274DD6,20200702.0,50.646907,30155929.0,25.0,Won,W,41.0,0.69,1220.0,NaN,611993,20200701.0,763.0
04701946-E052-44C9-BCB5-C6AFC2EBFF7E,20200702.0,3.769829,30155929.0,25.0,Won,W,41.0,0.69,1220.0,NaN,611993,20200701.0,773.0
D9E161D4-ACE6-47B5-ADB0-71FB3E95BF9A,20200702.0,220.875272,30155929.0,25.0,Won,W,41.0,0.69,1220.0,NaN,611993,20200701.0,766.0
A020C0C8-B478-4EC0-9769-9FA2618E33DE,20200702.0,9.754097,30155929.0,25.0,Won,W,41.0,0.70,1220.0,NaN,611993,20200701.0,757.0

In [74]:
# for i in df['material_ref'].unique():
#     print(i)

In [75]:
df.loc[df['material_ref'].isnull()==True ,'material_ref']='0'

In [76]:
df.isnull().sum()

item_date        0
quantity tons    0
customer         0
country          0
status           2
item type        0
application      0
thickness        0
width            0
material_ref     0
product_ref      0
delivery date    0
selling_price    0
dtype: int64

In [77]:
df['item_date']=df['item_date'].astype('str')
df['item_date']=df['item_date'].str.split('.',1).str[0]

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8928\3892607050.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df['item_date']=df['item_date'].str.split('.',1).str[0]

In [99]:
df['item_date']=pd.to_datetime(df['item_date'],format="%Y-%m-%d")

In [96]:
df.loc[df['item_date']=='19950000']='20201012'

In [97]:
df.loc[df['item_date']=='20191919']='20201012'

In [98]:
df['delivery date']

id
EC06F063-9DF0-440C-8764-0B0C05A4F6AE   2021-07-01
4E5F4B3D-DDDF-499D-AFDE-A3227EC49425   2021-04-01
E140FF1B-2407-4C02-A0DD-780A093B1158   2021-01-01
F8D507A0-9C62-4EFE-831E-33E1DA53BB50   2021-01-01
4E1C4E78-152B-430A-8094-ADD889C9D0AD   2021-03-01
                                          ...
DE633116-D1DF-4846-982E-55EFC3658A76   2020-07-01
A48374B1-E6DB-45F2-889A-1F9C27C099EB   2020-07-01
91643238-5C7B-4237-9A5F-63AE3D35F320   2020-07-01
7AFFD323-01D9-4E15-B80D-7D1B03498FC8   2020-07-01
AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC   2020-07-01
Name: delivery date, Length: 181664, dtype: datetime64[ns]

In [100]:
df['delivery date']=df['delivery date'].astype('str')
df['delivery date']=df['delivery date'].str.split('.',1).str[0]

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8928\826886549.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df['delivery date']=df['delivery date'].str.split('.',1).str[0]

In [101]:
df['delivery date']=pd.to_datetime(df['delivery date'],format="%Y-%m-%d")

In [102]:
df.loc[df['delivery date']=='30310101']='20201012'

In [103]:
df.loc[df['delivery date']=='20212222']='20201012'

In [104]:
df.head()

,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
id,,,,,,,,,,,,,
EC06F063-9DF0-440C-8764-0B0C05A4F6AE,2021-04-01,54.151139,30156308.0,28.0,Won,W,10.0,2.0,1500.0,DEQ1 S460MC,1670798778,2021-07-01,854.0
4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,2021-04-01,768.024839,30202938.0,25.0,Won,W,41.0,0.8,1210.0,104991,1668701718,2021-04-01,1047.0
E140FF1B-2407-4C02-A0DD-780A093B1158,2021-04-01,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,2021-01-01,644.33
F8D507A0-9C62-4EFE-831E-33E1DA53BB50,2021-04-01,202.411065,30349574.0,32.0,Won,S,59.0,2.3,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,2021-01-01,768.0
4E1C4E78-152B-430A-8094-ADD889C9D0AD,2021-04-01,785.526262,30211560.0,28.0,Won,W,10.0,4.0,2000.0,2_S275JR+AR-CL1,640665,2021-03-01,577.0

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181664 entries, EC06F063-9DF0-440C-8764-0B0C05A4F6AE to AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item_date      181664 non-null  datetime64[ns]
 1   quantity tons  181664 non-null  object
 2   customer       181664 non-null  object
 3   country        181664 non-null  object
 4   status         181664 non-null  object
 5   item type      181664 non-null  object
 6   application    181664 non-null  object
 7   thickness      181664 non-null  object
 8   width          181664 non-null  object
 9   material_ref   181664 non-null  object
 10  product_ref    181664 non-null  object
 11  delivery date  181664 non-null  datetime64[ns]
 12  selling_price  181664 non-null  object
dtypes: datetime64[ns](2), object(11)
memory usage: 23.4+ MB

In [106]:
# df.to_csv("all_clean_data_coper.csv")

In [107]:
df.isnull().sum()

item_date        0
quantity tons    0
customer         0
country          0
status           0
item type        0
application      0
thickness        0
width            0
material_ref     0
product_ref      0
delivery date    0
selling_price    0
dtype: int64

In [114]:
d=df[df['status'].isnull()]

In [115]:
df.drop(d.index,inplace=True)

In [116]:
df.isnull().sum()

item_date        0
quantity tons    0
customer         0
country          0
status           0
item type        0
application      0
thickness        0
width            0
material_ref     0
product_ref      0
delivery date    0
selling_price    0
dtype: int64

In [118]:
df.to_csv("coper_analysis1_data.csv")

In [117]:
d=df[df['status']=='20201012']
d

Empty DataFrame
Columns: [item_date, quantity tons, customer, country, status, item type, application, thickness, width, material_ref, product_ref, delivery date, selling_price]
Index: []

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder
# import numpy as np

# enc=OrdinalEncoder()
# # 

# for i in df1.columns:
#   if df1[i].dtype == 'object' and i != 'id':
#     col_name = i
#     df1[i] = enc.fit_transform(df1[[i]])
#     data = df1[i].sort_values().unique() # 0.0,1.0,2.0 - this is encoded value
#     globals()[col_name] = {}
#     decoded_data = enc.inverse_transform(df1[[i]])
#     decoded = sorted(np.unique(decoded_data)) # original value of dataframe - like decoded value
#     globals()[i] = dict(zip(decoded, data))